# Generated by Django 5.1.1 on 2024-10-09 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_rename_id_sensor_measurement_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='temperature_measured',
            new_name='temperature',
        ),
    ]
